### ISSUE TITLE
Possible Variation

### ISSUE THREAD

**Issue by ghost** [AndrewB330/EuclideanMST#2]
Is it possible to find Euclidean Maximum Spanning Tree using this code?

Also, are you sure that it's time complexity is NLogN? Because on my local machine a code with 2e5 points in 3-4 dimension is taking forever to finish

I am attaching the test data i used

[[TEST DATA](https://drive.google.com/file/d/1kzbXpl-AQNn0fSTZgtzWg8MUAhkQ1s91/view?usp=sharing)]
and it took 115322ms for the execution

For an algorithm with time complexity of N*log(n), i expected a execution time around 3 seconds 
Can please you help a little, i need it for a task?

**Comment by AndrewB330** [comment]
Hi!
**About time complexity:** Yeah, I know this, it can take a while for 4D+ dimensions.
But I quoted the original paper, that says about NlogN time complexity. (I also marked it with __*__ in readme, because it is very tricky moment)

It is actually NlogN in average, but starting at some bigger N, and for dimensions 4D+ it is about 10'000'000+ points, only after that point it will reach NlogN complexity. So as I said it is a tricky moment, but as I know there is no better algorithm yet, or at least I don't know about it.

**About your test case:** I will take a look on it. As you can see in my benchmarks, it should take less than 2 seconds for 50k points in 4D.

**Comment by AndrewB330** [comment]
@budbak Ok, so I've tried your test case, it finished in 15 seconds. The answer (total length) is `774042352.509533`.

Are you sure that you are using `KdTreeSolver`? Are you sure that you are building the program in `Release` mode?

**Comment by AndrewB330** [comment]
@budbak Also, I've noticed some activity on this repository, can I ask you, if you know, what is this? Is that some kind of university task?

**Comment by ghost** [comment]
Yes, i did use KDTreeSolver, I was finding Maximum Spanning Tree, so I did some changes, and maybe that bugged something. also from the paper, I think the time complexity is cNlogN where c is some kind of constant, related to points distribution

There is a programming contest on Codechef, you can read the statement of the problem( Link Below), it goes for 10 days, with some really hard problems, and they allow people to refer to online resources/code/repository published earlier. I thought this DualTreeBoruvka can help, but I can confirm it can't solve the above task.

The activity is probably because most people are referring to the implementation of the above algorithm in c++.

Here is the link.
https://www.codechef.com/OCT20A/problems/DDIMMST

I'll tell you the solution after it finishes :)

**Comment by AndrewB330** [comment]
@budbak Ah, ok, I see.

Yes, this algorithm can't help to solve this problem. It is designed **only for the minimum tree**, and only for the euclidean norm (but I think it can actually work for any norm).

But the original problem from CodeChef is very interesting, yeah. I think I see how to solve it, the 1-norm is the key here :) Good luck with the contest!
